# droptable にはMOB卵を入手する際に使用する本のドロップMOB/数/率を設定します
# droptable->MOB名->amount OR rate はそれぞれスペース二つずつネストさせて下さい。
# □--------------------------------------□
#  記載例
# □--------------------------------------□
# ドロップテーブル
# droptable:
#   EnderDragon:
#     amount: 3
#     rate: 1
#   Witch:
#     amount: 1
#     rate: 100
# □--------------------------------------□
#  本のタイトル
# title: '魔道書「えこたまご」'
# □--------------------------------------□
#  アイテム欄での表示名
# name: '魔道書「えこたまご」'
# □--------------------------------------□
#  著者名
# author: '神官えこ'
# □--------------------------------------□
#  ページ内容 [スペース2つとハイフン+内容]で1ページ分の情報です
#  本の最大ページ数／文字数の仕様を超える定義を記載した場合の動作は保障できません
# pages:
#   - 'この書物は生物を卵化する効果があります。対象に向かって右クリックで発動。使用後この書物は消滅します。次ページは対象生物一覧。'
#   - '§0BAT, §8BLAZE, §0CAVE_SPIDER, §8CHICKEN, §0COW, §8CREEPER, §0ENDERMAN, §8GHAST, §0MAGMA_CUBE, §8MUSHROOM_COW, §0OCELOT, §8PIG, §0PIG_ZOMBIE, §8SHEEP, §0SILVERFISH, §8SKELETON, §0SLIME, §8SQUID, §0VILLAGER, §8WITCH, §0WOLF, §8ZOMBIE'
# □--------------------------------------□


droptable:
  EnderDragon:
    amount: 3
    rate: 1
  Witch:
    amount: 1
    rate: 100
title: '魔道書「えこたまご」'
name: '魔道書「えこたまご」'
author: '神官えこ'
pages:
  - 'この書物は生物を卵化する効果があります。対象に向かって右クリックで発動。使用後この書物は消滅します。次ページは対象生物一覧。'
  - '§0BAT, §8BLAZE, §0CAVE_SPIDER, §8CHICKEN, §0COW, §8CREEPER, §0ENDERMAN, §8GHAST, §0MAGMA_CUBE, §8MUSHROOM_COW, §0OCELOT, §8PIG, §0PIG_ZOMBIE, §8SHEEP, §0SILVERFISH, §8SKELETON, §0SLIME, §8SQUID, §0VILLAGER, §8WITCH, §0WOLF, §8ZOMBIE'
