name: FastUse
main: xyz.sk7z.fastuse.FastUse
version: ${project.version}
api-version: 1.13
depend: [EcoFramework]
commands:
  fu:
    description: fastuse command.
    usage: /<command> [GLIDE,EAT] [ON/OFF]
    permission: fastuse
  fu glide:
    description: fastuse command.
    usage: /<command> glide [ON/OFF]
    permission: fastuse.glide
  fu eat:
    description: fastuse command.
    usage: /<command> eat [ON/OFF]
    permission: fastuse.eat


